# Generated by Django 5.2.12 on 2026-03-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户信息列表',
                'db_table': 'inventory_account',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='门店名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='门店编码')),
                ('manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.TextField(verbose_name='门店地址')),
                ('business_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='营业时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '门店信息',
                'verbose_name_plural': '门店信息列表',
                'db_table': 'inventory_store',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='单位名称')),
                ('type', models.CharField(choices=[('supplier', '供应商'), ('customer', '客户'), ('both', '既是供应商也是客户')], default='customer', max_length=20, verbose_name='单位类型')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行账号')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='税号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '来往单位',
                'verbose_name_plural': '来往单位列表',
                'db_table': 'inventory_supplier',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='支出名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='支付账户')),
            ],
            options={
                'verbose_name': '支出记录',
                'verbose_name_plural': '支出记录列表',
                'db_table': 'inventory_expense',
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='费用类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型编码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.expensetype', verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '费用类型',
                'verbose_name_plural': '费用类型列表',
                'db_table': 'inventory_expense_type',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收入类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型编码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.incometype', verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '收入类型',
                'verbose_name_plural': '收入类型列表',
                'db_table': 'inventory_income_type',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类列表',
                'db_table': 'inventory_product_category',
                'ordering': ['level', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='商品编号')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本价')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售价')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.account', verbose_name='关联账户')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory', verbose_name='商品分类')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品信息',
                'db_table': 'inventory_product',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('issue', models.TextField(verbose_name='故障描述')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='维修费用')),
                ('status', models.CharField(choices=[('pending', '待维修'), ('repairing', '维修中'), ('done', '已完成')], default='pending', max_length=20, verbose_name='维修状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.account', verbose_name='收款账户')),
                ('customer', models.ForeignKey(limit_choices_to={'type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='客户')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录列表',
                'db_table': 'inventory_repair',
            },
        ),
        migrations.CreateModel(
            name='RepairItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='使用数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='维修用料')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.repair', verbose_name='维修记录')),
            ],
            options={
                'verbose_name': '维修用料',
                'verbose_name_plural': '维修用料记录',
                'db_table': 'inventory_repairitem',
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货单价')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='支付账户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '采购记录',
                'verbose_name_plural': '采购记录列表',
                'db_table': 'inventory_stockin',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('position', models.CharField(choices=[('manager', '经理'), ('cashier', '收银员'), ('salesman', '销售员'), ('technician', '技术员'), ('other', '其他')], default='salesman', max_length=20, verbose_name='职位')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本工资')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='提成比例(%)')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '职员信息',
                'verbose_name_plural': '职员信息列表',
                'db_table': 'inventory_staff',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='销售数量')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售单价')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='总金额')),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='利润')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='收款账户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'type': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='客户')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录列表',
                'db_table': 'inventory_sale',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '交易流水',
                'verbose_name_plural': '交易流水记录',
                'db_table': 'inventory_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitialAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='期初余额')),
                ('initial_date', models.DateField(verbose_name='期初日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '初期建账',
                'verbose_name_plural': '初期建立账户',
                'db_table': 'inventory_initial_accounting',
                'unique_together': {('account', 'initial_date')},
            },
        ),
    ]
