# Generated by Django 4.1.13 on 2026-03-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户列表',
                'db_table': 'inventory_account',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户列表',
                'db_table': 'inventory_customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本价')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.account', verbose_name='关联账户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品列表',
                'db_table': 'inventory_product',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('issue', models.TextField(verbose_name='故障描述')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='维修费用')),
                ('status', models.CharField(choices=[('pending', '待维修'), ('repairing', '维修中'), ('done', '已完成')], default='pending', max_length=20, verbose_name='维修状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.account', verbose_name='收款账户')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录列表',
                'db_table': 'inventory_repair',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '交易流水',
                'verbose_name_plural': '交易流水记录',
                'db_table': 'inventory_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货单价')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='支付账户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录列表',
                'db_table': 'inventory_stockin',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='销售数量')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售单价')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='总金额')),
                ('profit', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='利润')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='收款账户')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer', verbose_name='客户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录列表',
                'db_table': 'inventory_sale',
            },
        ),
        migrations.CreateModel(
            name='RepairItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='使用数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='维修用料')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.repair', verbose_name='维修记录')),
            ],
            options={
                'verbose_name': '维修用料',
                'verbose_name_plural': '维修用料记录',
                'db_table': 'inventory_repairitem',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='支出名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.account', verbose_name='支付账户')),
            ],
            options={
                'verbose_name': '支出记录',
                'verbose_name_plural': '支出记录列表',
                'db_table': 'inventory_expense',
            },
        ),
    ]
