# Generated by Django 6.0.3 on 2026-03-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('', '无'), ('black', '黑色'), ('white', '白色'), ('red', '红色'), ('blue', '蓝色'), ('green', '绿色'), ('yellow', '黄色'), ('purple', '紫色'), ('pink', '粉色'), ('gold', '金色'), ('silver', '银色'), ('gray', '灰色'), ('orange', '橙色'), ('brown', '棕色'), ('custom', '其他')], default='', max_length=20, verbose_name='商品颜色'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='颜色代码(如:#FF0000)'),
        ),
    ]
