# Generated by Django 5.2.12 on 2026-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productcategory_brand_productcategory_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='商品备注'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='color',
            field=models.CharField(blank=True, choices=[('', '无'), ('black', '黑色'), ('white', '白色'), ('red', '红色'), ('blue', '蓝色'), ('green', '绿色'), ('yellow', '黄色'), ('purple', '紫色'), ('pink', '粉色'), ('gold', '金色'), ('silver', '银色'), ('gray', '灰色'), ('orange', '橙色'), ('brown', '棕色'), ('custom', '其他')], default='', max_length=20, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='specification',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='规格'),
        ),
    ]
