# Generated by Django 5.2.12 on 2026-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productcategory_remark_alter_productcategory_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_leaf_category',
            field=models.BooleanField(default=False, verbose_name='这是一个分类'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='分类编码'),
        ),
    ]
