# Generated by Django 5.2.12 on 2026-03-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productcategory_is_leaf_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='color',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='型号'),
        ),
    ]
