# Generated by Django 5.2.12 on 2026-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_productcategory_color_productcategory_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('', '无'), ('black', '黑色'), ('white', '白色'), ('red', '红色'), ('blue', '蓝色'), ('green', '绿色'), ('yellow', '黄色'), ('purple', '紫色'), ('pink', '粉色'), ('gold', '金色'), ('silver', '银色'), ('gray', '灰色'), ('orange', '橙色'), ('brown', '棕色')], default='', max_length=20, verbose_name='商品颜色'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='售价'),
        ),
    ]
