# Generated by Django 5.2.12 on 2026-04-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_color_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
    ]
