# Generated by Django 5.2.12 on 2026-04-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_leaf_category',
        ),
    ]
