# Generated by Django 5.2.12 on 2026-04-04 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_productcategory_is_leaf_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='下单日期')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='预计到货日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('delivered', '已发货'), ('received', '已收货'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订单总额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.account', verbose_name='付款账户')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单列表',
                'db_table': 'inventory_purchase_order',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='采购数量')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='已收货数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='采购单价')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计金额')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购订单明细',
                'verbose_name_plural': '采购订单明细列表',
                'db_table': 'inventory_purchase_order_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('receipt_date', models.DateField(auto_now_add=True, verbose_name='入库日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='入库总额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购入库单',
                'verbose_name_plural': '采购入库单列表',
                'db_table': 'inventory_purchase_receipt',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='入库单价')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计金额')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereceipt', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '采购入库单明细',
                'verbose_name_plural': '采购入库单明细列表',
                'db_table': 'inventory_purchase_receipt_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True, verbose_name='退货单号')),
                ('return_date', models.DateField(auto_now_add=True, verbose_name='退货日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退货总额')),
                ('reason', models.TextField(verbose_name='退货原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='退货人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购退货单',
                'verbose_name_plural': '采购退货单列表',
                'db_table': 'inventory_purchase_return',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='退货数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退货单价')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计金额')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereturn', verbose_name='退货单')),
            ],
            options={
                'verbose_name': '采购退货单明细',
                'verbose_name_plural': '采购退货单明细列表',
                'db_table': 'inventory_purchase_return_item',
            },
        ),
    ]
