# Generated by Django 5.2.12 on 2026-04-04 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchaseorder_purchaseorderitem_purchasereceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='当前库存')),
                ('min_quantity', models.IntegerField(default=10, verbose_name='最低库存预警')),
                ('max_quantity', models.IntegerField(default=1000, verbose_name='最高库存预警')),
                ('last_inbound_date', models.DateField(blank=True, null=True, verbose_name='最后入库日期')),
                ('last_outbound_date', models.DateField(blank=True, null=True, verbose_name='最后出库日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info', to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存列表',
                'db_table': 'inventory_stock',
            },
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_no', models.CharField(max_length=50, unique=True, verbose_name='盘点单号')),
                ('check_date', models.DateField(auto_now_add=True, verbose_name='盘点日期')),
                ('status', models.CharField(default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='盘点人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store', verbose_name='盘点门店')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点列表',
                'db_table': 'inventory_stock_check',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(verbose_name='系统库存')),
                ('actual_quantity', models.IntegerField(verbose_name='实际库存')),
                ('difference', models.IntegerField(default=0, verbose_name='差异数量')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('stock_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcheck', verbose_name='盘点单')),
            ],
            options={
                'verbose_name': '库存盘点明细',
                'verbose_name_plural': '库存盘点明细列表',
                'db_table': 'inventory_stock_check_item',
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('inbound', '入库'), ('outbound', '出库'), ('transfer_in', '调拨入库'), ('transfer_out', '调拨出库'), ('adjust', '盘点调整'), ('return', '退货')], max_length=20, verbose_name='记录类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('before_quantity', models.IntegerField(verbose_name='变动前数量')),
                ('after_quantity', models.IntegerField(verbose_name='变动后数量')),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联单号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水记录',
                'db_table': 'inventory_stock_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True, verbose_name='调拨单号')),
                ('transfer_date', models.DateField(auto_now_add=True, verbose_name='调拨日期')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_out', to='inventory.store', verbose_name='调出门店')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_in', to='inventory.store', verbose_name='调入门店')),
            ],
            options={
                'verbose_name': '库存调拨',
                'verbose_name_plural': '库存调拨列表',
                'db_table': 'inventory_stock_transfer',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='调拨数量')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer', verbose_name='调拨单')),
            ],
            options={
                'verbose_name': '库存调拨明细',
                'verbose_name_plural': '库存调拨明细列表',
                'db_table': 'inventory_stock_transfer_item',
            },
        ),
    ]
