# Generated by Django 5.2.12 on 2026-04-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stock_stockcheck_stockcheckitem_stockrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='inventory.purchaseorder', verbose_name='采购订单'),
        ),
    ]
