# Generated by Django 4.2 on 2026-04-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_purchasereceipt_purchase_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasereturn",
            options={
                "ordering": ["-return_date"],
                "verbose_name": "采购退货单",
                "verbose_name_plural": "采购退货单列表",
            },
        ),
        migrations.AlterField(
            model_name="purchasereturn",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.purchaseorder",
                verbose_name="采购订单",
            ),
        ),
    ]
