# Generated by Django 4.2 on 2026-04-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_purchasereturn_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereturn",
            name="purchase_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.purchasereceipt",
                verbose_name="入库单号",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereturn",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="退货原因"),
        ),
    ]
