# Generated by Django 4.2 on 2026-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_purchasereturn_purchase_receipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereturn",
            name="_stock_updated",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
