# Generated by Django 4.2 on 2026-04-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_purchasereturn__stock_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="出库单号"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(auto_now_add=True, verbose_name="出库日期"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="出库总额",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="出库人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "销售出库单",
                "verbose_name_plural": "销售出库单列表",
                "db_table": "inventory_sale_delivery",
                "ordering": ["-delivery_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "order_date",
                    models.DateField(auto_now_add=True, verbose_name="下单日期"),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="预计发货日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("confirmed", "已确认"),
                            ("shipped", "已发货"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="订单总额",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="已付金额",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="创建人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.account",
                        verbose_name="收款账户",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"type__in": ["customer", "both"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.supplier",
                        verbose_name="客户",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.staff",
                        verbose_name="销售人员",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.store",
                        verbose_name="销售门店",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售订单",
                "verbose_name_plural": "销售订单列表",
                "db_table": "inventory_sale_order",
                "ordering": ["-order_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="退货单号"
                    ),
                ),
                (
                    "return_date",
                    models.DateField(auto_now_add=True, verbose_name="退货日期"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="退货总额",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="退货原因"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="退货人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("_stock_updated", models.BooleanField(default=False, editable=False)),
                (
                    "sale_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.saledelivery",
                        verbose_name="出库单号",
                    ),
                ),
                (
                    "sale_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.saleorder",
                        verbose_name="销售订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售退货单",
                "verbose_name_plural": "销售退货单列表",
                "db_table": "inventory_sale_return",
                "ordering": ["-return_date"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="退货数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="退货单价"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="小计金额",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "return_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.salereturn",
                        verbose_name="退货单",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售退货单明细",
                "verbose_name_plural": "销售退货单明细列表",
                "db_table": "inventory_sale_return_item",
            },
        ),
        migrations.CreateModel(
            name="SaleOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="销售数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="销售单价"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="小计金额",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "sale_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.saleorder",
                        verbose_name="销售订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售订单明细",
                "verbose_name_plural": "销售订单明细列表",
                "db_table": "inventory_sale_order_item",
            },
        ),
        migrations.CreateModel(
            name="SaleDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="出库数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="出库单价"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="小计金额",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.saledelivery",
                        verbose_name="出库单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售出库单明细",
                "verbose_name_plural": "销售出库单明细列表",
                "db_table": "inventory_sale_delivery_item",
            },
        ),
        migrations.AddField(
            model_name="saledelivery",
            name="sale_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="inventory.saleorder",
                verbose_name="销售订单",
            ),
        ),
    ]
