# Generated by Django 4.2 on 2026-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_saledelivery_saleorder_salereturn_salereturnitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereceipt",
            name="is_stock_updated",
            field=models.BooleanField(default=False, verbose_name="库存是否已更新"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="type",
            field=models.CharField(
                choices=[
                    ("supplier", "供应商"),
                    ("customer", "客户"),
                    ("both", "既是供应商也是客户"),
                ],
                default="supplier",
                max_length=20,
                verbose_name="单位类型",
            ),
        ),
    ]
